# Environment Variables
export EDITOR=nvim
# Set the prompt
setopt PROMPT_SUBST
export PS1='%F{cyan}%~%f $(parse_git_branch)%# '
# GPG TTY for signing
export GPG_TTY=$(tty)

# Aliases
alias vi=nvim
alias vim=nvim

# Load Git completion
zstyle ':completion:*:*:git:*' script ~/.config/zsh/git-completion.zsh
fpath=(~/.zsh $fpath)

# Evaluations
eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(direnv hook zsh)"
if [[ $options[zle] = on ]]; then
  eval "$(fzf --zsh)"
fi
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"

# Completions
autoload -U +X compinit && compinit

# History
export HISTSIZE=20000
export HISTFILE="$HOME/.zsh_history"
export SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups
setopt hist_ignore_space
#
# Prevent tmux from using vi keybindings:
#    http://matija.suklje.name/zsh-vi-and-emacs-modes
bindkey -e

# Functions
function y () {
	local tmp="$(mktemp -t "yazi-cwd.XXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")"  && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]
	then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

# tat: tmux attach
function tat {
  name=$(basename `pwd` | sed -e 's/\.//g')

  if tmux ls 2>&1 | grep "$name"; then
    tmux attach -t "$name"
  elif [ -f .envrc ]; then
    direnv exec / tmux new-session -s "$name"
  else
    tmux new-session -s "$name"
  fi
}

# Function to get the current Git branch
function parse_git_branch() {
  git branch 2>/dev/null | sed -n -e 's/^\* \(.*\)/(\1)/p'
}

