# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Enable split into horizontal windows with custom working directory
bind-key '"' command-prompt -p "Target:" "splitw -c '%%'"

# Enable split into vertical windows with custom working directory
bind-key '%' command-prompt -p "Target:" "splitw -h -c '%%'"

